config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { invitations: "users/invitations" }
  resources :establishments do
    devise_scope :user do
      resource :invitations, controller: "users/invitations"
    end
    resources :menu_items
    resources :donates
    resources :claims
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get "/", to: 'establishments#index', constraints: RoleRouteConstraint.new { |user| user.superadmin_role? }
  # get "/", to: 'establishments#my', constraints: RoleRouteConstraint.new { |user| user.establishment_role? }
  # constraints(RoleRouteConstraint.new { |user| user.superadmin_role? }) do
  #   root to: 'establishments#index'
  # end
  # constraints(RoleRouteConstraint.new { |user| user.establishment_role? }) do
  #   root to: 'establishments#my'
  # end
  # constraints(RoleRouteConstraint.new { |user| !user.establishment_role? && user.superadmin_role? }) do
  #   root to: "home#index"
  # end
  root to: "home#index"
end

app/models/claim.rb
class Claim < Transaction
end

app/controllers/claims_controller.rb
class ClaimsController < ApplicationController
  before_action :set_establishment
  before_action :set_claim, only: [:show, :edit, :update, :destroy]

  # GET /claims
  # GET /claims.json
  def index
    @claims = Claim.all
  end

  # GET /claims/1
  # GET /claims/1.json
  def show
  end

  # GET /claims/new
  def new
    @claim = Claim.new
  end

  # GET /claims/1/edit
  def edit
  end

  # POST /claims
  # POST /claims.json
  def create
    @claim = @establishment.claims.build(claim_params.merge(user: current_user))

    respond_to do |format|
      if @claim.save
        format.html { redirect_to @establishment, notice: 'Claim was successfully created.' }
        format.json { render :show, status: :created, location: @claim }
      else
        format.html { redirect_to @establishment, alert: @claim.errors.full_messages.join(". ") }
        format.json { render json: @claim.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /claims/1
  # PATCH/PUT /claims/1.json
  def update
    respond_to do |format|
      if @claim.update(claim_params)
        format.html { redirect_to @establishment, notice: 'Claim was successfully updated.' }
        format.json { render :show, status: :ok, location: @claim }
      else
        format.html { render :edit }
        format.json { render json: @claim.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /claims/1
  # DELETE /claims/1.json
  def destroy
    @claim.destroy
    respond_to do |format|
      format.html { redirect_to claims_url, notice: 'Claim was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_claim
      @claim = Claim.find(params[:id])
    end

    def set_establishment
      @establishment = Establishment.find(params[:establishment_id])
    end

    # Only allow a list of trusted parameters through.
    def claim_params
      params.require(:claim).permit(:amount)
    end
end

app/helpers/claims_helper.rb
module ClaimsHelper
end

app/views/claims/_form.html.erb
<%= form_with(model: [claim.establishment, claim], local: true) do |form| %>
  <% if claim.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(claim.errors.count, "error") %> prohibited this claim from being saved:</h2>

      <ul>
        <% claim.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount, step: 0.01 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/claims/edit.html.erb
<h1>Editing Claim</h1>

<%= render 'form', claim: @claim %>

<%= link_to 'Back', @claim.establishment %>

app/views/claims/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Claims</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @claims.each do |claim| %>
      <tr>
        <td><%= link_to 'Show', claim %></td>
        <td><%= link_to 'Edit', edit_claim_path(claim) %></td>
        <td><%= link_to 'Destroy', claim, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Claim', new_claim_path %>

app/views/claims/new.html.erb
<h1>New Claim</h1>

<%= render 'form', claim: @claim %>

<%= link_to 'Back', claims_path %>

app/views/claims/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_claim_path(@claim) %> |
<%= link_to 'Back', claims_path %>