config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { invitations: "users/invitations" }
  resources :establishments do
    devise_scope :user do
      resource :invitations, controller: "users/invitations"
    end
    resources :menu_items
    resources :donates
    resources :claims
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get "/", to: 'establishments#index', constraints: RoleRouteConstraint.new { |user| user.superadmin_role? }
  # get "/", to: 'establishments#my', constraints: RoleRouteConstraint.new { |user| user.establishment_role? }
  # constraints(RoleRouteConstraint.new { |user| user.superadmin_role? }) do
  #   root to: 'establishments#index'
  # end
  # constraints(RoleRouteConstraint.new { |user| user.establishment_role? }) do
  #   root to: 'establishments#my'
  # end
  # constraints(RoleRouteConstraint.new { |user| !user.establishment_role? && user.superadmin_role? }) do
  #   root to: "home#index"
  # end
  root to: "home#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :establishments_user
  has_one :establishment, through: :establishments_user

  def role
    if superadmin_role?
      "Superadmin"
    elsif establishment_role?
      "Establishment"
    end
  end
end

app/controllers/users/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController
  private

    # this is called when creating invitation
    # should return an instance of resource class
    def invite_resource
      establishment = Establishment.find(params[:establishment_id])
      super do |user|
        establishment.users << user
        user.establishment_role = true
      end
    end

    def after_invite_path_for(inviter, invitee = nil)
      establishment_path(invitee.establishment)
    end
end

app/views/users/invitations/edit.html.erb
<h2><%= t "devise.invitations.edit.header" %></h2>

<%= form_for(resource, as: resource_name, url: invitation_path(resource_name), html: { method: :put }) do |f| %>
  <%= render "devise/shared/error_messages", resource: resource %>
  <%= f.hidden_field :invitation_token, readonly: true %>

  <% if f.object.class.require_password_on_accepting %>
    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit t("devise.invitations.edit.submit_button") %>
  </div>
<% end %>

app/views/users/invitations/new.html.erb
<h2><%= t "devise.invitations.new.header" %></h2>

<%= form_for(resource, as: resource_name, url: invitation_path(resource_name), html: { method: :post }) do |f| %>
<%#= form_for(resource, as: resource_name, url: establishment_invitations_path(Establishment.first), html: { method: :post }) do |f| %>
  <%= render "devise/shared/error_messages", resource: resource %>

  <% resource.class.invite_key_fields.each do |field| -%>
    <div class="field">
      <%= f.label field %><br />
      <%= f.text_field field %>
    </div>
  <% end -%>

  <div class="actions">
    <%= f.submit t("devise.invitations.new.submit_button") %>
  </div>
<% end %>