config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { invitations: "users/invitations" }
  resources :establishments do
    devise_scope :user do
      resource :invitations, controller: "users/invitations"
    end
    resources :menu_items
    resources :donates
    resources :claims
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get "/", to: 'establishments#index', constraints: RoleRouteConstraint.new { |user| user.superadmin_role? }
  # get "/", to: 'establishments#my', constraints: RoleRouteConstraint.new { |user| user.establishment_role? }
  # constraints(RoleRouteConstraint.new { |user| user.superadmin_role? }) do
  #   root to: 'establishments#index'
  # end
  # constraints(RoleRouteConstraint.new { |user| user.establishment_role? }) do
  #   root to: 'establishments#my'
  # end
  # constraints(RoleRouteConstraint.new { |user| !user.establishment_role? && user.superadmin_role? }) do
  #   root to: "home#index"
  # end
  root to: "home#index"
end

app/models/establishment.rb
class Establishment < ApplicationRecord
  has_many :menu_items, dependent: :destroy
  accepts_nested_attributes_for :menu_items,
    allow_destroy: true,
    reject_if: lambda { |attributes| attributes["name"].blank? || attributes["price"].blank? }
  has_and_belongs_to_many :users#, -> { where(users: {establishment: true}) }
  has_many :transactions, dependent: :destroy
  has_many :donates, dependent: :destroy
  has_many :claims, dependent: :destroy

  def balance
    Money.new(donates.sum(:amount_cents) - claims.sum(:amount_cents))
  end

  def coordinates
    [longitude, latitude]
  end

  def items_remained
    avg = Money.new(menu_items.average(:price_cents))
    avg == 0 || avg.nil? ? "Some" : (balance / avg).floor
  end
end

app/controllers/establishments_controller.rb
class EstablishmentsController < ApplicationController
  load_and_authorize_resource
  before_action :set_establishment, only: [:show, :edit, :update, :destroy]

  # GET /establishments
  # GET /establishments.json
  def index
    @establishments = Establishment.all
  end

  # GET /establishments/1
  # GET /establishments/1.json
  def show
  end

  # GET /establishments/new
  def new
    @establishment = Establishment.new
  end

  # GET /establishments/1/edit
  def edit
    @establishment.menu_items.build
  end

  # POST /establishments
  # POST /establishments.json
  def create
    @establishment = Establishment.new(establishment_params)

    respond_to do |format|
      if @establishment.save
        format.html { redirect_to @establishment, notice: 'Establishment was successfully created.' }
        format.json { render :show, status: :created, location: @establishment }
      else
        format.html { render :new }
        format.json { render json: @establishment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /establishments/1
  # PATCH/PUT /establishments/1.json
  def update
    respond_to do |format|
      if @establishment.update(establishment_params)
        format.html { redirect_to @establishment, notice: 'Establishment was successfully updated.' }
        format.json { render :show, status: :ok, location: @establishment }
      else
        format.html { render :edit }
        format.json { render json: @establishment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /establishments/1
  # DELETE /establishments/1.json
  def destroy
    @establishment.destroy
    respond_to do |format|
      format.html { redirect_to establishments_url, notice: 'Establishment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def my
    redirect_to current_user.establishment
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_establishment
      @establishment = Establishment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def establishment_params
      params.require(:establishment).permit(:name, :longitude, :latitude, :address, menu_items_attributes: [:id, :name, :price, :_destroy])
    end
end

app/helpers/establishments_helper.rb
module EstablishmentsHelper
end

app/views/establishments/_form.html.erb
<%= form_with(model: establishment, local: true) do |form| %>
  <% if establishment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(establishment.errors.count, "error") %> prohibited this establishment from being saved:</h2>

      <ul>
        <% establishment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>

    <%= form.label :longitude %>
    <%= form.text_field :longitude %>

    <%= form.label :latitude %>
    <%= form.text_field :latitude %>

    <%= form.label :address %>
    <%= form.text_field :address %>

    <% if establishment.menu_items.any? %>
    <div>Menu items:<div>
    <ul>
    <%= form.fields_for :menu_items do |menu_item_form| %>
      <li>
      <%= menu_item_form.label :name %>
      <%= menu_item_form.text_field :name %>
      <%= menu_item_form.label :price %>
      <%= menu_item_form.text_field :price %>
      <%= menu_item_form.label :_destroy %>
      <%= menu_item_form.check_box :_destroy %>
      </li>
    <% end %>
    <ul>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/establishments/edit.html.erb
<h1>Editing Establishment</h1>

<%= render 'form', establishment: @establishment %>

<%= link_to 'Show', @establishment %> |
<%= link_to 'Back', establishments_path %>

app/views/establishments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Establishments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @establishments.each do |establishment| %>
      <tr>
        <td><%= establishment.name %></td>
        <% if can?(:show, establishment) %><td><%= link_to 'Show', establishment %></td><% end %>
        <% if can?(:edit, establishment) %><td><%= link_to 'Edit', edit_establishment_path(establishment) %></td><% end %>
        <% if can?(:destroy, establishment) %><td><%= link_to 'Destroy', establishment, method: :delete, data: { confirm: 'Are you sure?' } %></td><% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can?(:new, Establishment) %><%= link_to 'New Establishment', new_establishment_path %><% end %>

app/views/establishments/new.html.erb
<h1>New Establishment</h1>

<%= render 'form', establishment: @establishment %>

<%= link_to 'Back', establishments_path %>

app/views/establishments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @establishment.name %>
</p>

<p>
  <strong>Balance:</strong>
  <%= humanized_money_with_symbol @establishment.balance %>
</p>

<% if can?(:manage_users, Establishment) %>
<div>Users</div>
<%= form_for :user, url: establishment_invitations_path(@establishment) do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.submit "Invite" %>
<% end %>
<ul>
<% @establishment.users.each do |user| %>
  <li><%= user.email %></li>
<% end %>
</ul>
<% end %>

<div>Menu items</div>
<ul>
  <% @establishment.menu_items.each do |menu_item| %>
  <li>
    <span><%= menu_item.name %></span>
    <span><%= humanized_money_with_symbol menu_item.price %></span>
  </li>
  <% end %>
</ul>

<% if can?(:index, Transaction, @establishment) %>
<div>Transactions</div>
<ul>
  <% @establishment.transactions.each do |transaction| %>
  <li>
    <%= transaction.is_a?(Donate) ? "Donate" : "Claim" %>&nbsp;
    <%= l transaction.created_at, format: :short %>,
    <%= humanized_money_with_symbol transaction.amount %>
    from <%= transaction.user.email %>
    <%= link_to("Edit", edit_establishment_claim_path(@establishment, transaction)) if transaction.is_a?(Claim) %>
  </li>
  <% end %>
</ul>
<% end %>

<% if can?(:create, Donate) %>
<div>Donate</div>
<%= render "donates/form", establishment: @establishment, donate: @establishment.donates.build %>
<% end %>

<% if can?(:create, Claim) %>
<div>Claim</div>
<%= render "claims/form", establishment: @establishment, claim: @establishment.claims.build %>
<% end %>

<% if can?(:edit, @establishment) %><%= link_to 'Edit', edit_establishment_path(@establishment) %> |<% end %>
<%= link_to 'Back', establishments_path %>